application: omarvssaurya
version: 1
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /log
  script: log.app
- url: /delete
  script: delete.app
- url: /addfriend
  script: addfriend.app
- url: /deletefriend
  script: deletefriend.app
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
